name: Deploy CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
    - name: Upload production-files
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: ./dist
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
            name: production-files
            path: ./dist

      - name: Deploy to GiHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist

  
