name: Deploy CI

on:
  push:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
    - name: Upload production-files
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./dist
    
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
            name: production-files
            path: ./dist

      - name: Deploy to GiHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: production-files